#!/bin/bash

list_subproject() {
    SUBPROJECT=$1
    ls \
        src/$SUBPROJECT.hpp \
        src/$SUBPROJECT/* \
        test/$SUBPROJECT.test.cpp \
        benchmark/*$SUBPROJECT.cpp
}

LOG_FILE="code_quality.log"

SRC_FILES=" \
$(list_subproject factorial) \
$(list_subproject fibonacci) \
$(list_subproject burglars_night_out) \
"

echo $SRC_FILES

./script/make && \
clang-tidy \
    --quiet \
    -p "build/compile_commands.json" \
    --config-file=.clang-tidy \
    ${SRC_FILES} \
    --export-fixes=$LOG_FILE
