#!/bin/sh

git submodule update --init --recursive


cd dependency/catch
cmake --build build -H. -DBUILD_TESTING=OFF
sudo cmake --build build/ --target install
cd ../../

cd dependency/itertools
cmake --build build
sudo cmake --build build/ --target install
