#!/bin/sh

git submodule update --init --recursive


cd dependency/catch
cmake -Bbuild -H. -DBUILD_TESTING=OFF
sudo cmake --build build/ --target install
cd ../../

cd dependency/itertools
cmake -Bbuild
sudo cmake --build build/ --target install
