name: Test
on:
  push:
    branches:
      - trunk
jobs:
  test-gcc:
    runs-on: ubuntu-22.04
    env:
      CC: /usr/bin/gcc
      CXX: /usr/bin/g++
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: install gcc
        shell: bash
        run:  |
              sudo apt update
              sudo apt install gcc-11 g++-11 cmake
      - name: install catch2
        run: ./script/install_catch
      - name: test
        run: ./script/test
  test-clang:
    runs-on: ubuntu-22.04
    env:
      CC: /usr/bin/clang
      CXX: /usr/bin/clang++
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: install clang
        shell: bash
        run:  |
              sudo apt update
              sudo apt install clang
      - name: install catch2
        run: ./script/install_catch
      - name: test
        run: ./script/test
