name: Test
on: [push]
jobs:
  Test:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: Install GCC11
        shell: bash
        run:  |
              sudo apt update
              sudo apt install gcc-11 g++-11 cmake
      - name: install catch2
        run: |
          git submodule update --init --recursive
          cd dependency/catch
          cmake -Bbuild -H. -DBUILD_TESTING=OFF
          sudo cmake --build build/ --target install
      - name: test
        run: ./script/test
